name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - run: ./gradlew checkstyleMain
        working-directory: app
      - run: ./gradlew test
        working-directory: app
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
           JACOCO_SOURCE_PATH: ${{ github.workspace }}/app/src/main/java
        with:
           coverageCommand: make report
           workingDirectory: app
           coverageLocations: "${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco"

